// Browser-safe contract for the optional Python recognition engine. No credentials or API calls.
const words = text => text.trim().split(/\s+/u).filter(Boolean).join(" ");
export const STRATEGY_LABELS = {
  portrait: "Portrait · 9:16 (recommended)", narrative: "Narrative · longer phrases",
  shorts: "Short phrases · social", calm: "Calm · longer reading", word: "One word · timing draft"
};

export function parseAudioReview(input) {
  const data = typeof input === "string" ? JSON.parse(input.replace(/^\uFEFF/, "")) : input;
  if (data?.format !== "content-machine-audio-review" || data.version !== 1) throw new Error("Choose a .review.json file generated by the audio recognition command.");
  const duration = data.audio?.duration;
  if (!Number.isFinite(duration) || duration <= 0 || duration > 28800) throw new Error("The audio review has an invalid duration (maximum 8 hours).");
  if (typeof data.script !== "string" || !data.script.trim()) throw new Error("The audio review is missing its original script.");
  const entries = Object.entries(data.strategies ?? {});
  if (!entries.length || entries.length > 30) throw new Error("The audio review has no usable strategies.");
  const strategies = Object.create(null);
  for (const [name, value] of entries) {
    if (!/^[a-z0-9_-]+$/i.test(name) || ["__proto__", "constructor", "prototype"].includes(name)) throw new Error("Invalid strategy name.");
    if (!Array.isArray(value.cues) || !value.cues.length || value.cues.length > 10000) throw new Error(`Invalid cues in ${name}.`);
    let previousEnd = 0;
    const cues = value.cues.map(c => {
      if (!Number.isFinite(c.start) || !Number.isFinite(c.end) || c.start < 0 || c.end <= c.start || c.end > duration + .001 || c.start < previousEnd - .001) throw new Error(`Invalid or overlapping timestamps in ${name}.`);
      if (typeof c.text !== "string" || !c.text.trim() || c.text.split("\n").length > 2) throw new Error(`Invalid subtitle text in ${name}.`);
      previousEnd = c.end;
      return { start: c.start, end: c.end, text: c.text, needs_review: c.needs_review === true,
        reason: Array.isArray(c.reason) ? c.reason.filter(x => typeof x === "string").slice(0, 8) : [],
        onset_adjustment_ms: Number.isFinite(c.onset_adjustment_ms) ? c.onset_adjustment_ms : 0,
        median_pitch_hz: Number.isFinite(c.median_pitch_hz) ? c.median_pitch_hz : null,
        graphemes_per_second: Number.isFinite(c.graphemes_per_second) ? c.graphemes_per_second : null };
    });
    if (words(cues.map(c => c.text).join(" ")) !== words(data.script)) throw new Error(`The ${name} captions do not preserve the supplied script. Review the source before importing.`);
    strategies[name] = { cues };
  }
  if (!Object.hasOwn(strategies, data.defaultStrategy)) throw new Error("The default strategy is missing.");
  return { format: data.format, version: 1, script: data.script, strategies, defaultStrategy: data.defaultStrategy,
    waveform: Array.isArray(data.waveform) && data.waveform.length <= 300000 && data.waveform.every(x => Number.isFinite(x) && x >= 0) ? data.waveform : [],
    model: typeof data.model === "string" ? data.model : "Cloudflare ASR",
    audio: { duration, name: typeof data.audio.name === "string" ? data.audio.name : "audio", sha256: data.audio.sha256 },
    cost: Number.isFinite(data.cost?.successful_list_estimate_usd) ? data.cost.successful_list_estimate_usd : null };
}

// Styled Unicode sidecar for ASS-aware players. Resolve/Premiere use the SRT exports.
export function buildAss(cues, { aspect = "9:16", font = "Noto Sans Devanagari", size = 60, color = "#ffffff", position = "bottom", look = "outline" } = {}) {
  const dimensions = { "9:16": [1080, 1920], "16:9": [1920, 1080], "1:1": [1080, 1080], "4:5": [1080, 1350] };
  const [width, height] = dimensions[aspect] ?? dimensions["9:16"];
  const align = { bottom: 2, center: 5, top: 8 }[position] ?? 2;
  const hex = /^#[0-9a-f]{6}$/i.test(color) ? color.slice(1) : "ffffff";
  const assColor = `&H00${hex.slice(4, 6)}${hex.slice(2, 4)}${hex.slice(0, 2)}`;
  const family = String(font).replace(/[,\r\n]/g, " ");
  const fontSize = Number.isFinite(Number(size)) ? Math.min(120, Math.max(12, Number(size))) : 60;
  const portrait = aspect === "9:16";
  const marginV = Math.round(height * (position === "top" ? .12 : portrait ? 350 / 1920 : aspect === "16:9" ? .07 : .16));
  const stamp = t => {
    let n = Math.round(t * 100); const h = Math.floor(n / 360000); n %= 360000;
    const m = Math.floor(n / 6000); n %= 6000;
    return `${h}:${String(m).padStart(2, "0")}:${String(Math.floor(n / 100)).padStart(2, "0")}.${String(n % 100).padStart(2, "0")}`;
  };
  const text = s => s.replace(/\\/g, "＼").replace(/{/g, "(").replace(/}/g, ")").replace(/\r/g, "").replace(/\n/g, "\\N");
  const header = `[Script Info]\nScriptType: v4.00+\nPlayResX: ${width}\nPlayResY: ${height}\nWrapStyle: 2\nScaledBorderAndShadow: yes\n\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,${family},${fontSize},${assColor},&H0000D7FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,${look === "box" ? 3 : 1},${look === "plain" ? 0 : 3},${look === "plain" ? 0 : 1},${align},${portrait ? 96 : Math.round(width * .06)},${portrait ? 140 : Math.round(width * .06)},${marginV},1\n\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n`;
  return header + cues.map(c => `Dialogue: 0,${stamp(c.start)},${stamp(c.end)},Default,,0,0,0,,${text(c.text)}`).join("\n") + "\n";
}
