export const GRADE = "Photoreal cinematic historical reenactment film still. Shallow depth of field with the background falling soft. Palette: fired-brick red #8a3b26, aged sal-wood brown #4a2f1f, oil-lamp amber #d9902f, gilded copper #b8862b, smoke grey #6e6a64, lime-washed off-white #e6dfd0. Deep shadows, warm amber highlights, fine natural film grain, realistic skin with visible pores and texture rather than smoothed plastic.";

export const KANTIPUR = "Specifically Malla-era Newar Kathmandu (the kingdom of Kantipur) in the 1600s, and specifically NOT a Mughal Delhi court, NOT a Rajasthani palace, NOT a Tibetan monastery, NOT Chinese, NOT a Thai or Burmese temple, NOT modern Nepal: exposed red brick buildings with intricately carved dark sal-wood windows and lattice screens, multi-tiered pagoda temples with sloping clay-tiled roofs, gilded copper finials and carved diagonal roof struts, stone-paved courtyards, stone water spouts, stone lion guardians, brass oil lamps; noblemen in the long pleated jama robe gathered at the waist with a patuka sash over fitted churidar trousers and a wrapped turban.";

export const TIBET = "Specifically 1600s Tibet near Lhasa, and specifically NOT Nepal, NOT Chinese, NOT Mongolian: whitewashed stone and rammed-earth buildings with inward-sloping walls, black trapezoid window frames and flat roofs, a barren brown high plateau under hard blue sky ringed by bare mountains; Tibetan officials in thick maroon and gold brocade chuba robes with fur-trimmed hats; yak-butter lamps and painted thangka scrolls indoors.";

export const NEG = "No text, no captions, no signage, no lettering and no logos anywhere in the frame. No flags, no banners, no pennants and no national flags of any kind. Period-true objects only: no glass windows, no electric light, no plastic, no modern objects. Natural anatomy, correct hands with five fingers, no cloned faces.";

export const C = {
  king: "PRATAP MALLA, the Newar king of Kantipur: early thirties, lean and upright, warm wheat-brown skin, oval face with high cheekbones, dark almond eyes under straight heavy brows, a thin neatly curled black moustache and no beard. He wears a long pleated ivory-white jama robe with gold-embroidered cuffs, a crimson patuka sash, and a tall wrapped ivory turban set with a gold jewelled crest and a small white plume. Large gold hoop earrings in both ears, a three-strand pearl necklace, a red vermilion tika on the forehead. Proud bearing, chin raised. Never bearded, never a Mughal emperor, never a Western crown.",
  bhim: "KAJI BHIM MALLA, loyal minister and general of Kantipur: mid-forties, broad-shouldered and sturdy, weathered bronze-brown skin with sun lines at the eyes, square face, a full thick black moustache touched with grey, greying sideburns, calm steady dark eyes, a small old scar through the right eyebrow. He wears a knee-length saffron-ochre jama coat over churidar trousers, a dark indigo patuka sash with a sheathed khukuri tucked at the front, a plain maroon wrapped turban without jewels, a single silver ring on the right thumb, a rudraksha bead necklace. Straight-backed, dignified and open-faced. Never young, never lean, never jewelled like a king.",
  oldking: "LAXMI NARASIMHA MALLA, the deposed old king: late sixties, frail and thin, pale wheat-brown skin, sunken cheeks, a long unkempt white beard and white moustache, white hair loose to the shoulders, tired hollow eyes. He wears a faded, creased ivory jama robe with no jewels and a thin grey wool shawl, a faded red thread on the right wrist. Never crowned, never jewelled, never robust.",
  ojha: "MAHADEV OJHA, a senior courtier: late fifties, plump and soft-bodied, light brown skin, round clean-shaven face, shaved head with a single long tuft of hair at the crown, three horizontal sandal-paste lines on the forehead with a red dot, narrow watchful eyes. He wears a white dhoti and a white upper shawl with a saffron border, a thin sacred thread across the chest, a rudraksha rosary in one hand. Never turbaned, never armed.",
  naradev: "NARADEV, a courtier: forties, tall and thin, sharp narrow face, a small pointed black beard and thin moustache, sallow brown skin. He wears a dark bottle-green jama robe with a gold patuka sash and a small green wrapped turban, a gold ring on each forefinger. Never armed.",
  maya: "MAYA SINGH, a courtier of military rank: late thirties, heavy-set and thick-necked, dark brown skin, a heavy black moustache and dark stubble, heavy brows. He wears a deep indigo-blue jama robe, a low loosely wound black cloth turban sitting close on the brow with no clasp or pin, a silver-hilted curved sword in a black scabbard at his hip. Never a Sikh dastar, never a tall peaked turban.",
  wife: "THE WIFE OF KAJI BHIM MALLA, a Newar noblewoman: early thirties, slender, warm golden-brown skin, oval face, large dark eyes, a straight nose with a small gold stud on the left nostril, a small dark mole above the right corner of her lips, long black hair parted in the middle with a line of red sindoor in the parting. She wears a deep red sari with a broad gold border draped over her head, a fitted red blouse, heavy gold earrings, stacked gold bangles on both wrists, a gold chain forehead ornament. Composed and still, grief held in the jaw. Never a film-bridal look, never heavy make-up, never smiling."
};
